name: trash_trek
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flame: 1.8.0
  flutter:
    sdk: flutter
  flutter_gif: ^0.0.4
  rive: ^0.12.4
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flame_audio: ^2.0.3
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/game/
    - assets/audio/audio.mp3
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"

  image: assets/images/icon.png

  android_12:
    color: "#ffffff"
    image: assets/images/icon.png
